Create an endpoint, custom exporter and instrumentation for Hilla
vaadin/observability-kit pull request #207
Opened 2023-04-19 08:26 UTC by MatthewVaadin

Creates a Hilla endpoint that will process a JSON string. This is called by a custom traces exporter module that takes a reference to the endpoint. The endpoint constructor is then instrumented to inject a callback to do the export from the agent.

2023-04-20 08:32 UTC, heruan requested changes
Still a draft, so this is just a placeholder request to remember to move the Hilla endpoint to its own module.

2023-04-20 13:06 UTC, Lodin approved these changes
LGTM

2023-04-20 13:06 UTC, Lodin commented on observability-kit-starter/src/main/resources/META-INF/resources/frontend/components/HillaEndpointExporter.ts
> +  protected _endpoint: (string) => void;
Do I understand correctly that this exporter is designed extendable? 🤔

2023-04-26 06:32 UTC, heruan requested changes

2023-04-26 06:32 UTC, heruan commented on pom.xml
> +        <hilla.version>2.0.0</hilla.version>
We should target Hilla 2.1 here to be sure the kit works with the latest platform.
```suggestion
        <hilla.version>2.1-SNAPSHOT</hilla.version>
```

2023-04-26 06:32 UTC, heruan commented on observability-kit-starter-hilla/pom.xml
> +        <cvdl.name>vaadin-observability-kit</cvdl.name>
Let's use `hilla-observability-kit` as the product slug, following the same convention we used for SSO Kit:
```suggestion
        <cvdl.name>hilla-observability-kit</cvdl.name>
```

2023-04-26 12:01 UTC, heruan approved these changes

2023-04-26 12:02 UTC, merged