refactor: set up new directory structure
vaadin/observability-kit pull request #228
Opened 2023-05-30 21:00 UTC by Lodin

2023-05-31 05:15 UTC, MatthewVaadin submitted a review, later dismissed

2023-05-31 07:27 UTC, heruan requested changes
Thanks! I'll also check this out and give it a try 🚀

2023-05-31 09:29 UTC, manolo commented
Remember to modify TS steps in the build before merging this https://bender.vaadin.com/admin/editBuildRunners.html?id=buildType:Vaadin6weekProjects_VaadinObservability_VaadinObservabilityRelease

2024-01-22 13:46 UTC, heruan commented
Closing this upon the decision to keep the existing Java/Maven based repository structure. Changes related to TypeScript compilation and use of NX might be ported to a different PR.

2024-01-22 13:46 UTC, closed without merging